### ISSUE TITLE
agent-js: implement new segment format

### ISSUE THREAD

**Issue by such** [stratumn/js-indigocore#202]
Segments must now declare their type.
State might also be splitted into `var` and `jar`.

**Comment by simonvadee** [comment]
This is postponed until we have a use-case or a specific need for it.

**Comment by such** [comment]
Actually we still need to provide a way to declare a type in actions? Do we want to default to the action name? It might be a bit confusing...

**Comment by simonvadee** [comment]
(discussed IRL), the third argument of `this.append(state, meta, type)` already provides a way to modify the state.
However we might want to add a plugin that copies the action name to the link type instead of having a default value like we currently do.

**Comment by simonvadee** [comment]
Deprecated.
