### ISSUE TITLE
agent-js: use decorators to extend agent actions info

### ISSUE THREAD

**Issue by jeremie-stratumn** [stratumn/js-indigocore#232]
For example, we could decorate the function with the actual schema to be used when calling the function: 
```Javascript
export default {
  @schema({foo: {type: 'string'}, bar: {type: 'bool'}})
  init(foo, bar) {
    ...
  }

  @schema({smthg: {type: 'object'}})
  do(smthg) {
    ...
  }

}
```

one immediate application for that is that agent-ui could parse this info (if exposed via http api) and render a proper form when creating new segments

**Comment by simonvadee** [comment]
Will reopen if needed
