### ISSUE TITLE
Evidence visualizers

### ISSUE THREAD

**Issue by t-bast** [stratumn/js-indigocore#254]
It would be cool to be able to visualize evidence (BTC, Tendermint).
This could be done as a stand-alone react component that could be then integrated in Agent-UI.

**Comment by t-bast** [comment]
I think it's quite a lot of work after looking at it more closely, and it's worth doing it well when we have enough time.
It requires good front-end design skills to make nice animations/visualisations so I don't feel up to the task ;)

**Comment by simonvadee** [comment]
Deprecated.
