### ISSUE TITLE
agent-js: add a way to retrieve latest segments

### ISSUE THREAD

**Issue by such** [stratumn/js-indigocore#9]
In cases when the agent or the client application goes offline and its store is distributed, it would be nice if we could have a way to make it retrieve missed segments.
In this case, the client application is probably aware of the last segment it received and would be able to provide it to the agent. Right now there is no way to retrieve segments that have been stored passed a certain date or after a given segment.

**Comment by simonvadee** [comment]
Not needed for now, will reopen if needed
